apiVersion: v1
kind: Service
metadata:
  name: kolibri
  labels:
    app: kolibri
spec:
  selector:
    app: kolibri
  ports:
    - name: http
      port: 8080
      targetPort: http
    - name: zipcontent
      port: 8311
      targetPort: zipcontent
